import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Dashboard/Navbars/NavbarDynamic";
import { NavProvider } from "@/components/Dashboard/Context/Navcontext";
import ThemeProvider from "./ThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0`}
      >
         <ThemeProvider> {/* 🆕 wrap everything */}
<svg width="0" height="0" style={{ position: "absolute" }}>
  <defs>
    <clipPath id="notifClip" clipPathUnits="objectBoundingBox">
      <path
        d="
          M0 0.90
          C0 0.98 0.015 1 0.035 1
          H0.5348
          H0.9638
          C0.985 1 1 0.98 1 0.90
          V0.24
          C1 0.24 1 0.14 0.9638 0.14
          H0.5701
          C0.548 0.14 0.5348 0.10 0.5348 0.06
          C0.5348 0.03 0.52 0 0.5 0
          H0.035
          C0.015 0 0 0.03 0 0.06
          V0.90
          Z
        "
      />
    </clipPath>
  </defs>
</svg>
          <NavProvider>
            <div className="flex-shrink-0">
              <Navbar />
            </div>
            <div className="flex-1 overflow-auto w-full">
              {children}
            </div>
          </NavProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}