import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Dashboard/Navbars/NavbarDynamic";
import { NavProvider } from "@/components/Dashboard/Context/Navcontext";
import ThemeProvider from "./ThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0`}
      >
         <ThemeProvider> {/* 🆕 wrap everything */}
          <NavProvider>
            <div className="flex-shrink-0">
              <Navbar />
            </div>
            <div className="flex-1 overflow-auto w-full">
              {children}
            </div>
          </NavProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}